---
  - name: Install and Config Docker
    hosts: elk
    become: true
    tasks:
      # apt module
    - name: Install docker.io
      apt:
        update_cache: yes
        force_apt_get: yes
        name: docker.io
        state: present

      # apt module
    - name: Install pip3
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

      # pip module (It will default to pip3)
    - name: Install Python Docker Module
      pip:
        name: docker
        state: present

      # command module
    - name: Increase virtual memory
      command: sysctl -w vm.max_map_count=262144

      # sysctl module
    - name: Use more memory
      sysctl:
        name: vm.max_map_count
        value: 262144
        state: present
        reload: yes

      # Docker_container module
    - name: download and launch a docker elk container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        # Elk ports
        published_ports:
          -  5601:5601
          -  9200:9200
          -  5044:5044

    - name: Enable service docker on boot
      systemd:
        name: docker
        enabled: yes
